In [17]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
## load dataset
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv.zip', compression='zip')

movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [19]:
## selecting useful columns

movies = movies[['movieId', 'title', 'genres']]
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [20]:
## Filling missing values
movies.fillna('', inplace=True)

In [21]:
## Converting text data
tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(movies['genres'])

In [22]:
## calculate similarity
cosine_sim = cosine_similarity(tfidf_matrix)

In [23]:
## Creating Recommendation function
def recommend_movies(movie_name):

    idx = movies[movies['title'] == movie_name].index[0]

    similarity_scores = list(enumerate(cosine_sim[idx]))

    similarity_scores = sorted(similarity_scores,
                               key=lambda x: x[1],
                               reverse=True)

    similarity_scores = similarity_scores[1:11] # Changed from 1:6 to 1:11 for top 10 recommendations

    for movie in similarity_scores:
        print(movies.iloc[movie[0]].title)

In [24]:
## Testing the system
recommend_movies('Jumanji (1995)')

Indian in the Cupboard, The (1995)
NeverEnding Story III, The (1994)
Escape to Witch Mountain (1975)
Darby O'Gill and the Little People (1959)
Return to Oz (1985)
NeverEnding Story, The (1984)
NeverEnding Story II: The Next Chapter, The (1990)
Santa Claus: The Movie (1985)
Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)
Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The (2005)

In [27]:
## User input
movie_name = input("Enter a movie name: ")

# Check if 'movies' DataFrame exists and if the movie is found in it.
# This prevents the IndexError if the movie name is not in the dataset.
if 'movies' in globals() and movie_name in movies['title'].values:
    recommend_movies(movie_name)
else:
    print(f"Movie '{movie_name}' not found in the dataset or 'movies' DataFrame is not loaded.")
    print("Please ensure you enter an exact movie title (e.g., 'Toy Story (1995)').")
    print("Also, make sure all previous cells, especially the one defining the 'recommend_movies' function (cell 'qkOC396dK0qw'), have been run.")

Enter a movie name: Toy Story (1995)
Antz (1998)
Toy Story 2 (1999)
Adventures of Rocky and Bullwinkle, The (2000)
Emperor's New Groove, The (2000)
Monsters, Inc. (2001)
Wild, The (2006)
Shrek the Third (2007)
Tale of Despereaux, The (2008)
Asterix and the Vikings (Astérix et les Vikings) (2006)
Turbo (2013)

In [28]:
# show top 10 recommendations instead of 5
# The modification was moved to the recommend_movies function to fix the NameError.

In [29]:
## Error handling

def recommend_movies(movie_name):

    if movie_name not in movies['title'].values:
        print("Movie not found")
        return

    idx = movies[movies['title'] == movie_name].index[0]

    similarity_scores = list(enumerate(cosine_sim[idx]))

    similarity_scores = sorted(similarity_scores,
                               key=lambda x: x[1],
                               reverse=True)

    similarity_scores = similarity_scores[1:11]

    for movie in similarity_scores:
        print(movies.iloc[movie[0]].title)

In [30]:
## project successfully completed...